version: "3.8"

services:
  ws:
    image: realstraw/sbt
    working_dir: /acdc/ws
    volumes:
      - ./:/acdc/ws
    environment:
      POSTGRES_PASSWORD: "acdc"
    ports:
      - 9001:9000
    command:
      sbt ws/run
  db:
    image: postgres
    volumes:
      - acdc-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "acdc"

volumes:
  acdc-postgres-data:
